sudo qemu-system-x86_64 \
  -m 4G \
  -cpu core2duo \
  -boot order=d \
  -drive file=android.iso,media=cdrom \
  -drive file=android.img,format=raw \
  -drive file=virtio-win.iso,media=cdrom \
  -device rtl8139,netdev=n0 -netdev user,id=n0 \
  -device usb-ehci,id=usb,bus=pci.0,addr=0x4 \
  -device usb-tablet \
  -vnc :0 \
  -smp cores=2 \
  -accel tcg,thread=multi \
